export type Integration = {
  slug: string;
  name: string;
  vendor: string;
  icon: string;
  type: string;
  transport: 'Direct HTTP' | 'Local connector';
  status: string;
  intro: string;
  settings: string;
  prerequisites: string[];
  steps: string[];
  code?: string;
  language?: string;
  restart: string;
  troubleshooting: string[];
  security: string[];
  note?: string;
};

const endpoint = 'https://example.com/wp-json/wp-command-center/v1/mcp';
const token = 'siteradian_REPLACE_WITH_YOUR_TOKEN';

export const integrations: Integration[] = [
  {
    slug: 'chatgpt-codex', name: 'Codex in ChatGPT Desktop', vendor: 'OpenAI', icon: 'codex.svg', type: 'Desktop app · Codex mode', transport: 'Direct HTTP', status: 'Connection tested',
    intro: 'Use the Codex workspace inside the ChatGPT desktop app. Normal ChatGPT conversations do not use this local MCP connection.',
    settings: '~/.codex/config.toml (shared with Codex CLI)',
    prerequisites: ['The ChatGPT desktop app with Codex available', 'A public HTTPS WordPress site', 'A fresh SiteRadian token'],
    steps: ['Open SiteRadian → Settings → Connections → Assistants.', 'Choose Codex in ChatGPT Desktop and create access.', 'Run the displayed credential command, then the native Codex registration command.', 'Fully quit and reopen ChatGPT Desktop.', 'Switch from ChatGPT to Codex and run the verification prompt.'],
    code: `launchctl setenv SITERADIAN_TOKEN '${token}'\n\ncodex mcp add 'siteradian' \\\n  --url '${endpoint}' \\\n  --bearer-token-env-var 'SITERADIAN_TOKEN'`, language: 'shell',
    restart: 'Fully quit the desktop app—not only its window—then reopen it so the new environment value is inherited.',
    troubleshooting: ['If Codex reports a missing token, repeat the SiteRadian credential command and fully restart the app.', 'If the server is absent, run codex mcp list and confirm siteradian is registered.', 'Regular ChatGPT chats cannot see this local MCP server; use Codex mode.'],
    security: ['The Codex config stores the environment-variable name, not the raw token.', 'Revoke the token in SiteRadian to remove access.'],
  },
  {
    slug: 'codex-cli', name: 'Codex CLI', vendor: 'OpenAI', icon: 'codex.svg', type: 'Terminal app', transport: 'Direct HTTP', status: 'Connection tested',
    intro: 'Register SiteRadian with Codex, then launch Codex from the terminal session that holds the token.',
    settings: '~/.codex/config.toml',
    prerequisites: ['Codex CLI installed and signed in', 'A public HTTPS WordPress site', 'A fresh SiteRadian token'],
    steps: ['Open SiteRadian → Settings → Connections → Assistants.', 'Choose Codex CLI and create access.', 'Important: keep this terminal open.', 'Run the token command, registration command, and Codex launch in this same terminal.', 'Ask Codex to run the read-only system information check.'],
    code: `export SITERADIAN_TOKEN='${token}'\n\ncodex mcp add 'siteradian' \\\n  --url '${endpoint}' \\\n  --bearer-token-env-var 'SITERADIAN_TOKEN'\n\ncodex --ask-for-approval on-request`, language: 'shell',
    restart: 'Start Codex in this same terminal. Do not open a different Terminal or Warp tab for this step.',
    troubleshooting: ['Environment variable SITERADIAN_TOKEN is not set: return to the terminal where you exported it, or export a valid token again in the new terminal before starting Codex.', 'MCP registration persists; the terminal environment value does not. Do not recreate the registration if codex mcp list already shows siteradian.'],
    security: ['Do not save the token in your shell profile by default.', 'The registration stores only the environment-variable name.', 'Use an appropriately scoped token and revoke it when no longer needed.'],
    note: 'Keep this terminal open. Run the token command and start Codex in the same terminal session.',
  },
  {
    slug: 'claude-desktop', name: 'Claude Desktop', vendor: 'Anthropic', icon: 'claude.svg', type: 'Desktop app', transport: 'Local connector', status: 'Connection tested',
    intro: 'Claude Desktop uses SiteRadian’s small local connector because this client expects a local command-based MCP server.',
    settings: 'macOS: ~/Library/Application Support/Claude/claude_desktop_config.json · Windows: %APPDATA%\\Claude\\claude_desktop_config.json',
    prerequisites: ['Claude Desktop installed', 'Node.js installed on the computer running Claude', 'A fresh SiteRadian token'],
    steps: ['Choose Claude Desktop in SiteRadian Connections and create access.', 'Copy the keyed SiteRadian entry generated by the plugin.', 'Open Claude Desktop’s configuration file.', 'Merge the entry inside the existing mcpServers object; do not replace unrelated servers.', 'Restart Claude Desktop and run the verification prompt.'],
    code: `"siteradian": {\n  "command": "bash",\n  "args": ["-c", "# Copy the complete connector command generated by SiteRadian"],\n  "env": {\n    "SITERADIAN_MCP_URL": "${endpoint}",\n    "SITERADIAN_TOKEN": "${token}"\n  }\n}`, language: 'json',
    restart: 'Quit and reopen Claude Desktop after saving its configuration.',
    troubleshooting: ['No tools usually means Node.js is missing or the connector entry was placed outside mcpServers.', 'A 401 means the token is missing, expired, revoked, or copied incorrectly.', 'Use the complete generated connector command from your own site; it includes the correct plugin URL and version.'],
    security: ['The connector is served by your own SiteRadian installation, not npm.', 'Treat the configuration file as sensitive because it contains the token.'],
  },
  {
    slug: 'claude-code', name: 'Claude Code', vendor: 'Anthropic', icon: 'claude.svg', type: 'Terminal app', transport: 'Direct HTTP', status: 'Certified',
    intro: 'Claude Code connects directly over HTTPS and is registered with one native command—no configuration file to edit.',
    settings: 'Registered with claude mcp add',
    prerequisites: ['Claude Code installed and authenticated', 'A public HTTPS WordPress site', 'A fresh SiteRadian token'],
    steps: ['Choose Claude Code in SiteRadian Connections.', 'Create a scoped token.', 'Copy and run the generated native command.', 'Start a fresh Claude Code session.', 'Ask it to run system_info once, read-only.'],
    code: `claude mcp add --transport http 'siteradian' '${endpoint}' \\\n  --header 'Authorization: Bearer ${token}'`, language: 'shell',
    restart: 'Start a new Claude Code session after registration.',
    troubleshooting: ['The endpoint URL is positional; do not add an unsupported --url flag.', 'A 401 means the bearer token is invalid or no longer active.', 'Do not retry a pending approval—open the approval link instead.'],
    security: ['The command contains the token; keep it out of shared logs and shell history.', 'Claude cannot approve its own pending SiteRadian request.'],
  },
  {
    slug: 'antigravity-cli', name: 'Antigravity CLI', vendor: 'Google', icon: 'antigravity.png', type: 'Terminal app · agy', transport: 'Direct HTTP', status: 'Connection tested',
    intro: 'Antigravity CLI is a separate Google client from Gemini CLI and uses its own command and configuration file.',
    settings: '~/.gemini/config/mcp_config.json',
    prerequisites: ['Antigravity CLI (agy) installed', 'A public HTTPS WordPress site', 'A fresh read-only token for the first test'],
    steps: ['Choose Antigravity CLI and create read-only access.', 'Use the file-permission preparation shown in SiteRadian.', 'Run the generated agy mcp add command.', 'Exit any existing agy session and start a new one.', 'Use /mcp, then ask for system_info.'],
    code: `agy mcp add --header 'Authorization: Bearer ${token}' 'siteradian' '${endpoint}'`, language: 'shell',
    restart: 'Exit the current agy process and start a fresh one.',
    troubleshooting: ['Flags must precede the server name.', 'agy mcp list confirms registration only; /mcp in a fresh session confirms the live connection.', 'This is not Gemini CLI—do not use Gemini’s settings file shape.'],
    security: ['The native global configuration stores the bearer token. Protect it with user-only permissions.', 'Keep the token-bearing command out of history and shared logs.'],
  },
  {
    slug: 'gemini-cli', name: 'Gemini CLI', vendor: 'Google', icon: 'gemini.svg', type: 'Terminal app · gemini', transport: 'Direct HTTP', status: 'Account-limited test',
    intro: 'Gemini CLI uses a native registration command. Some individual accounts may be directed by Google to Antigravity instead.',
    settings: '~/.gemini/settings.json',
    prerequisites: ['Gemini CLI installed', 'An eligible Gemini Code Assist account', 'A public HTTPS WordPress site and fresh token'],
    steps: ['Choose Gemini CLI in SiteRadian Connections.', 'Create access.', 'Run the generated native command from a private terminal.', 'Trust the working folder if Gemini marks the server Disabled.', 'Restart Gemini and run the read-only verification prompt.'],
    code: `gemini mcp add 'siteradian' '${endpoint}' \\\n  --transport http \\\n  --scope user \\\n  --header 'Authorization: Bearer ${token}'`, language: 'shell',
    restart: 'Restart Gemini CLI after registration.',
    troubleshooting: ['If Google reports that the client is unavailable for your account, use a supported eligible account or Antigravity CLI.', 'Disabled can indicate an untrusted workspace rather than a broken server.', 'The native command preserves unrelated Gemini settings.'],
    security: ['The token is stored inline in Gemini’s settings file; do not commit or share it.', 'Revoke access from SiteRadian when finished.'],
  },
  {
    slug: 'cursor', name: 'Cursor', vendor: 'Anysphere', icon: 'cursor.svg', type: 'Code editor', transport: 'Direct HTTP', status: 'Connection tested',
    intro: 'Cursor connects directly to SiteRadian over HTTPS. The plugin provides a reviewed install action and a manual JSON fallback.',
    settings: '~/.cursor/mcp.json',
    prerequisites: ['Cursor installed', 'A public HTTPS WordPress site', 'A fresh SiteRadian token'],
    steps: ['Choose Cursor and create access.', 'Use the Install in Cursor action when available.', 'Approve the SiteRadian server entry.', 'Restart Cursor.', 'Open MCP settings, confirm SiteRadian is connected, and run system_info.'],
    code: `{"mcpServers":{"siteradian":{"url":"${endpoint}","headers":{"Authorization":"Bearer ${token}"}}}}`, language: 'json',
    restart: 'Restart Cursor after installing or editing the server configuration.',
    troubleshooting: ['For manual setup, merge only the siteradian entry; do not overwrite existing servers.', 'A model High Load message is a Cursor/model issue, not proof that the WordPress connection failed.', 'Check Cursor MCP settings for the server’s connection state.'],
    security: ['The manual file contains the token and must not be committed.', 'Prefer the scoped token generated for this connection.'],
  },
  {
    slug: 'continue', name: 'Continue for VS Code', vendor: 'Continue Dev', icon: 'continue.svg', type: 'VS Code extension', transport: 'Local connector', status: 'Connection tested',
    intro: 'Continue uses a YAML list entry and SiteRadian’s local connector. It also needs its own tool-capable chat model.',
    settings: '~/.continue/config.yaml (Main Config)',
    prerequisites: ['Continue installed in VS Code', 'Node.js installed locally', 'A tool-capable model configured in Continue', 'A fresh SiteRadian token'],
    steps: ['Choose Continue in SiteRadian Connections and create access.', 'If mcpServers is absent, copy the complete block. Otherwise copy only the indented SiteRadian list entry.', 'Save Continue’s Main Config.', 'Reload VS Code.', 'Select a tool-capable model and run system_info.'],
    code: `mcpServers:\n  - name: siteradian\n    command: bash\n    args:\n      - -c\n      - "# Copy the complete connector command generated by SiteRadian"\n    env:\n      SITERADIAN_MCP_URL: ${endpoint}\n      SITERADIAN_TOKEN: ${token}`, language: 'yaml',
    restart: 'Reload VS Code after updating Continue’s configuration.',
    troubleshooting: ['Do not create a second mcpServers key.', 'If Continue says Select model, configure a tool-capable model first.', 'No tools usually means Node.js or the local connector is unavailable.'],
    security: ['The YAML contains the token; keep it out of source control.', 'The connector comes from your own WordPress site.'],
  },
  {
    slug: 'github-copilot', name: 'GitHub Copilot in VS Code', vendor: 'GitHub / Microsoft', icon: 'github-copilot.svg', type: 'Copilot Agent mode', transport: 'Direct HTTP', status: 'Connection tested',
    intro: 'VS Code stores the token in secure input storage while the MCP file contains only a credential reference.',
    settings: 'Command Palette → MCP: Open User Configuration',
    prerequisites: ['Current VS Code with GitHub Copilot Agent mode', 'A public HTTPS WordPress site', 'A fresh SiteRadian token'],
    steps: ['Choose GitHub Copilot in VS Code and create access.', 'Open the MCP user configuration from the Command Palette.', 'Paste the exact generated configuration; the root key must be servers.', 'Start SiteRadian and enter the token when VS Code prompts.', 'In Copilot Agent mode, run system_info once.'],
    code: `{"servers":{"siteradian":{"type":"http","url":"${endpoint}","headers":{"Authorization":"Bearer \${input:siteradian-token-example}"}}},"inputs":[{"type":"promptString","id":"siteradian-token-example","description":"SiteRadian token","password":true}]}`, language: 'json',
    restart: 'Restart the SiteRadian MCP server from VS Code after entering the secure value.',
    troubleshooting: ['The root key is servers, not mcpServers.', 'If an OAuth or client-ID screen appears, cancel it and update the stored SiteRadian token.', 'A unique input id prevents a revoked value being silently reused. Use the generated id from the plugin.'],
    security: ['The configuration file does not contain the raw token.', 'VS Code prompts for it and retains it in secure storage.'],
  },
  {
    slug: 'opencode', name: 'OpenCode', vendor: 'Anomaly', icon: 'opencode.svg', type: 'Terminal app', transport: 'Direct HTTP', status: 'Connection tested',
    intro: 'OpenCode registers the remote SiteRadian server with one native command.',
    settings: '~/.config/opencode/opencode.jsonc',
    prerequisites: ['OpenCode installed', 'A public HTTPS WordPress site', 'A fresh SiteRadian token'],
    steps: ['Choose OpenCode and create access.', 'Run the generated opencode mcp add command.', 'Restart OpenCode.', 'Confirm the siteradian server appears.', 'Ask it to run system_info read-only.'],
    code: `opencode mcp add 'siteradian' \\\n  --url '${endpoint}' \\\n  --header 'Authorization=Bearer ${token}'`, language: 'shell',
    restart: 'Restart OpenCode after registration.',
    troubleshooting: ['Use Authorization=Bearer in the command’s KEY=VALUE header format.', 'Do not run opencode mcp auth; that starts OAuth, which SiteRadian does not use.', 'A 401 means the header or token is missing.'],
    security: ['The generated command contains the token; keep it private.', 'Native registration preserves existing servers.'],
  },
  {
    slug: 'command-code', name: 'Command Code', vendor: 'Command Code', icon: 'command-code.svg', type: 'Terminal app', transport: 'Direct HTTP', status: 'Connection tested',
    intro: 'Command Code uses its verified native MCP registration path and requires no local connector.',
    settings: '~/.commandcode/mcp.json',
    prerequisites: ['Command Code installed', 'A public HTTPS WordPress site', 'A fresh SiteRadian token'],
    steps: ['Choose Command Code and create access.', 'Copy the generated native command.', 'Run it in a private terminal.', 'Start a fresh Command Code session.', 'Ask for system_info once, read-only.'],
    code: `cmd mcp add \\\n  --transport http \\\n  --scope user \\\n  --header 'Authorization: Bearer ${token}' \\\n  'siteradian' '${endpoint}'`, language: 'shell',
    restart: 'Start a fresh Command Code process after registration.',
    troubleshooting: ['A message about OAuth can appear during unauthenticated discovery; there is no OAuth step.', 'Use the access token header generated by SiteRadian.', 'Prefer the native command over manually editing the shared file.'],
    security: ['The command contains the token.', 'Never paste it into shared chat, logs, or source control.'],
  },
  {
    slug: 'muse-code', name: 'Muse Code', vendor: 'Meta', icon: 'muse-code.svg', type: 'Terminal app · Experimental group', transport: 'Direct HTTP', status: 'Connection tested',
    intro: 'Muse Code is Meta’s standalone terminal coding agent, distinct from the Muse Spark model/API.',
    settings: '~/.config/muse/settings.json',
    prerequisites: ['Muse Code installed, authenticated, and attached to an eligible plan', 'A public HTTPS WordPress site', 'A fresh SiteRadian token'],
    steps: ['Choose Muse Code under Other / Experimental.', 'Create access.', 'Prepare the settings directory without replacing an existing file.', 'Keep schema_version set to 1 and merge the generated siteradian entry inside mcp_servers.', 'Restart Muse and run system_info.'],
    code: `{"schema_version":1,"mcp_servers":{"siteradian":{"transport":"streamable_http","url":"${endpoint}","headers":{"Authorization":"Bearer ${token}"}}}}`, language: 'json',
    restart: 'Restart Muse Code after saving settings.',
    troubleshooting: ['Keep schema_version: 1; Muse rejects a settings file that omits it.', 'Merge the server entry rather than replacing unrelated settings.', 'Muse Spark is not the same product or configuration surface.'],
    security: ['The settings file contains the token.', 'Muse MCP tools run outside Muse’s own filesystem/network sandbox; SiteRadian scope and approvals remain the relevant WordPress controls.'],
  },
];

export const integrationBySlug = new Map(integrations.map(item => [item.slug, item]));
